name: Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
    - name: Run unit tests
      shell: bash
      run: |
        cd test
        ./test.sh -V
